### ISSUE TITLE
project exhibits a woeful lack of release management and testing

### ISSUE THREAD

**Issue by josh-m-sharpe** [capacitor-community/fcm#45]
Exhibits:
https://github.com/capacitor-community/fcm/issues/43
https://github.com/capacitor-community/fcm/issues/44

I just spend 45 minutes "fixing" the issues in #43 only to realize #44 existed (and has been closed, but the OP there seems to think it's still broken an additional configuration needs to happen.)

Should I bother with 1.0.6 or should I wait for 1.0.7?

What steps are being taken to ensure that releases for this repo are actually production ready?

**Comment by stewwan** [comment]
#43 and #44 were fixed in 1.0.6 and it's production ready.

see the [example](https://github.com/capacitor-community/fcm/tree/master/example) and always check the [changelog](https://github.com/capacitor-community/fcm/blob/master/CHANGELOG.md).

please note that we're not part of ionic team, we're all contributors trying to solve a common need. Also the migration process has only started last week, so bear with us.

Thanks

**Comment by josh-m-sharpe** [comment]
@stewwan Yea, I understand you're not part of the ionic team, but please don't push your QA onto the community.  If you're going out of your way to rebrand something and call it "1.0" do your due diligence first.  The fact that android wouldn't build at all tells me you hadn't even bothered to do a production build using this repo.

**Comment by matheusdavidson** [comment]
@josh-m-sharpe this plugin helped me in many projects and they are all in production, this is called open source, therefore, community staff, if it doesn't suits you, send a PR instead of bluff words around to shows us your own rage and shame. 

Thank you, looking forward for your PR, or send me a check and i'll fix it for you ;]
